---
# tasks file for system_upgrade - Windows
- name: system_upgrade - upgrade all packages - Windows
  ansible.windows.win_updates:
    category_names: '*'
    reboot: "{{ system_upgrade_windows_reboot }}"
    reboot_timeout: 3600
